# Perfil padrão (desenvolvimento local)
spring.profiles.active=dev
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/estacao_meteorologica
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=8211

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Upload de arquivos (futuro)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB